name: Unity License Activation Test

on:
  workflow_dispatch:
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  activateAndThenReturnLicense:
    name: Activate and Return License
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-activate@v2          
      # Uncomment below for pro licenses
      #- uses: game-ci/unity-return-license@v2
